### ISSUE TITLE
Electron Rebuild step failing in CircleCI

### ISSUE THREAD

**Issue by sdc224** [electron/electron-rebuild#372]
Hello,

I have updated electron to 9.0.4, now almost all the CI scripts are working fine except CircleCI, which is throwing 

```bash
Error output:

Error output:
error /home/circleci/repo/app/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/circleci/repo/app/node_modules/keytar
Output:
/home/circleci/repo/app/node_modules/node-abi/index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 9.0.4 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/home/circleci/repo/app/node_modules/node-abi/index.js:30:9)
    at module.exports (/home/circleci/repo/app/node_modules/prebuild-install/rc.js:73:57)
    at Object.<anonymous> (/home/circleci/repo/app/node_modules/prebuild-install/bin.js:9:25)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

N.B.: Here `keytar` is one of my native dependency(as I am using two package.json structure)

I have already seen issues regarding `node-abi`, where it says `yarn upgrade` is enough to stop these issues. I have already done all those steps. There is no error throwing in my local or any other CI (azure-pipelines, Github Actions, appveyor).

I don't know whether it is the correct place to ask it, maybe there is an issue from circleci, or maybe I'm missing something silly.

My CircleCi config:
```yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test-except-e2e

```

Please help me 😥😥
